---
name: 'Grafana'
configurationClass:
  name: 'GrafanaConfiguration'
  package: 'com.exclamationlabs.connid.base.grafana.configuration'
rest: true # io-error-retries
service: true # service-url
results: true
security:
  httpBasicAuth: true
custom:
  items:
    required:
      separateOrgAssociation:
        type: boolean
        order: 100
        display: 'separateOrgAssociation.display'
        help: 'separateOrgAssociation.help'
      defaultOrgRole:
        type: string
        order: 110
        default: 'Viewer'
        display: 'defaultOrgRole.display'
        help: 'defaultOrgRole.help'
      updateDashBoards:
        type: boolean
        order: 150
        display: 'updateDashBoards.display'
        help: 'updateDashBoards.help'
    optional:
      lokiURL:
        type: string
        order: 120
        display: 'lokiURL.display'
        help: 'lokiURL.help'
      lokiUser:
        type: string
        order: 130
        display: 'lokiUser.display'
        help: 'lokiUser.help'
      lokiPassword:
        type: string
        order: 140
        confidential: true
        display: 'lokiPassword.display'
        help: 'lokiPassword.help'
      dashboardTemplate:
        type: string
        order: 160
        display: 'dashboardTemplate.display'
        help: 'dashboardTemplate.help'
helpText:
  serviceUrl:
    order: 10
    display: 'serviceUrl.display'
    help: 'serviceUrl.help'

