---
name: 'Grafana'
configurationClass:
  name: 'GrafanaConfiguration'
  package: 'com.exclamationlabs.connid.base.grafana.configuration'
rest: true # io-error-retries
service: true # service-url
results: true
security:
  httpBasicAuth: true
custom:
  items:
    required:
      separateOrgAssociation:
        type: boolean
        default: 'false'
        order: 3001
        display: 'separateOrgAssociation.display'
        help: 'separateOrgAssociation.help'
      defaultOrgRole:
        type: string
        order: 3010
        default: 'Viewer'
        display: 'defaultOrgRole.display'
        help: 'defaultOrgRole.help'
      defaultTimeZone:
        type: string
        order: 3020
        default: 'UTC'
        display: 'defaultTimeZone.display'
        help: 'defaultTimeZone.help'
      updateDashBoards:
        type: boolean
        default: 'false'
        order: 3055
        display: 'updateDashBoards.display'
        help: 'updateDashBoards.help'
    optional:
      lokiURL:
        type: string
        order: 3030
        display: 'lokiURL.display'
        help: 'lokiURL.help'
      lokiUser:
        type: string
        order: 3031
        display: 'lokiUser.display'
        help: 'lokiUser.help'
      lokiPassword:
        type: string
        order: 3032
        confidential: true
        display: 'lokiPassword.display'
        help: 'lokiPassword.help'
      dashboardTemplate:
        type: string
        order: 3060
        display: 'dashboardTemplate.display'
        help: 'dashboardTemplate.help'
helpText:
  serviceUrl:
    order: 10
    display: 'serviceUrl.display'
    help: 'serviceUrl.help'

